# fly.toml app configuration file generated for murmur-chat-hidden-moon-1149 on 2024-01-22T17:24:06+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "murmur-chat-hidden-moon-1149"
primary_region = "hkg"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
