# fly.toml app configuration file generated for murmur-chat on 2024-01-22T15:41:31+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "murmur-chat"
primary_region = "hkg"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
